// v4 additive bounded resource scan. Only FETCH already-observed
// query-free resources with the original scoped client. No brute forcing.
package scanner

import (
	"context"
	"fmt"
	"net/url"
	"sort"
	"strings"
	"sync"

	"funnelrecon/internal/secretanalyzer"
)

// secretResourceEligible is intentionally NOT a path brute-forcer: a resource
// must have been observed by the live probe or crawler before it can be fetched.
// Skip query-bearing links (potential GET side effects), JS (already analyzed),
// API routes, action routes, binary files, and passive-only historical URLs.
func secretResourceEligible(raw string, origins map[string]bool) bool {
	if !origins["live"] && !origins["crawl"] {
		return false
	}
	u, err := url.Parse(raw)
	if err != nil || u.RawQuery != "" || IsJS(raw) || IsStaticAsset(raw) || IsPotentialAPI(raw) {
		return false
	}
	// The existing form-fetch safety check handles extensionless HTML pages.
	if safeHTMLFetchPath(raw) {
		return true
	}
	// Explicitly linked text/config resources may be inspected, but no names
	// are guessed and no new paths are generated by this stage.
	path := strings.ToLower(u.Path)
	for _, extension := range []string{".json", ".txt", ".xml", ".yml", ".yaml", ".config", ".env"} {
		if strings.HasSuffix(path, extension) {
			return true
		}
	}
	return false
}

// DiscoverSecretResources supplements the original crawl/JS/form stages.
// It uses the same scoped, private-IP-blocking, redirect-checked, globally
// rate-limited HTTP client. Each worker holds at most one capped response body.
// No endpoint enumeration, form submission or secret validation is performed.
func (c *Client) DiscoverSecretResources(ctx context.Context, sources map[string]map[string]bool, workers, maxResources int, maxBody int64, detector *secretanalyzer.Detector, progress Progress, emit func(string)) ([]secretanalyzer.Finding, []string, int) {
	if maxResources <= 0 {
		return nil, nil, 0
	}
	resourceURLs := make([]string, 0)
	for raw, origins := range sources {
		if secretResourceEligible(raw, origins) {
			resourceURLs = append(resourceURLs, raw)
		}
	}
	// Prefer seed/crawl URLs to historical ones, and keep selection repeatable.
	sort.Slice(resourceURLs, func(i, j int) bool {
		a, b := sources[resourceURLs[i]]["live"], sources[resourceURLs[j]]["live"]
		if a != b {
			return a
		}
		return resourceURLs[i] < resourceURLs[j]
	})
	warnings := []string{}
	if len(resourceURLs) > maxResources {
		warnings = append(warnings, fmt.Sprintf("secret resource cap: retained %d of %d observed URLs", maxResources, len(resourceURLs)))
		resourceURLs = resourceURLs[:maxResources]
	}
	if maxBody > 1<<20 {
		maxBody = 1 << 20 // Bound extra worker memory regardless of -max-body.
	}
	if progress != nil {
		progress("Secrets", 0, len(resourceURLs))
	}
	type result struct {
		findings []secretanalyzer.Finding
		failed   bool
		checked  bool
	}
	jobs := make(chan string, workers)
	results := make(chan result, workers)
	var wg sync.WaitGroup
	for i := 0; i < workers; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for raw := range jobs {
				if ctx.Err() != nil {
					results <- result{failed: true}
					continue
				}
				body, typ, _, err := c.Fetch(ctx, raw, false, maxBody)
				if err != nil {
					results <- result{failed: true} // Never log raw URL/error details.
					continue
				}
				if !secretanalyzer.TextResource(typ, body) {
					results <- result{checked: true}
					continue
				}
				results <- result{checked: true, findings: detector.Detect(safeWatchURLString(raw), body)}
			}
		}()
	}
	go func() {
		defer close(results)
		for _, raw := range resourceURLs {
			select {
			case jobs <- raw:
			case <-ctx.Done():
				close(jobs)
				wg.Wait()
				return
			}
		}
		close(jobs)
		wg.Wait()
	}()
	found := []secretanalyzer.Finding{}
	failed, checked, completed := 0, 0, 0
	for r := range results {
		completed++
		if r.failed {
			failed++
		}
		if r.checked {
			checked++
		}
		found = append(found, r.findings...)
		if emit != nil && len(r.findings) > 0 {
			emit(fmt.Sprintf("Secret indicators in a text resource: %d (values never displayed)", len(r.findings)))
		}
		if progress != nil {
			progress("Secrets", completed, len(resourceURLs))
		}
	}
	if failed > 0 {
		warnings = append(warnings, fmt.Sprintf("secret resource scan: %d fetches failed or exceeded limits; no raw credentials or URLs logged", failed))
	}
	sort.Slice(found, func(i, j int) bool {
		a, b := found[i], found[j]
		return a.Source+a.Type+a.Fingerprint < b.Source+b.Type+b.Fingerprint
	})
	return found, warnings, checked
}
